-- =============================================================
-- K&P Love — Step 3: Seed Users
-- Run AFTER 01_tables.sql
--
-- ⚠️  IMPORTANT: These password hashes were generated by running:
--     python database/generate_seed_sql.py
--
-- The hashes below are REAL Argon2id hashes:
--   Kashish's password = "Preshna"
--   Preshna's password = "Kashish"
--
-- DO NOT modify the hash strings — they will stop working.
-- =============================================================

-- Remove any placeholder rows from schema.sql (if run before)
DELETE FROM users WHERE username IN ('Kashish', 'Preshna');

-- Insert the two predefined users with Argon2id-hashed passwords
INSERT INTO users (
    username,
    display_name,
    role,
    password_hash,
    online,
    created_at,
    updated_at
)
VALUES
(
    'Kashish',
    'Kashish Shrestha',
    'boyfriend',
    -- Argon2id hash of password: "Preshna"
    -- Generated with: argon2-cffi m=65536 t=3 p=4
    '$argon2id$v=19$m=65536,t=3,p=4$hoMsbUVf39Y05e6yAhFkEw$5vaSadcTGhWv3sxN+e0l4hvmSVeYy7znNGV/TPY+Xkk',
    FALSE,
    NOW(),
    NOW()
),
(
    'Preshna',
    'Preshna GC',
    'girlfriend',
    -- Argon2id hash of password: "Kashish"
    -- Generated with: argon2-cffi m=65536 t=3 p=4
    '$argon2id$v=19$m=65536,t=3,p=4$jLsHMlK91R8IUboykJe6pw$fxwl9CYVEa1bwl1M9H1qIcfai6mbiDipEiY0H3Q9izw',
    FALSE,
    NOW(),
    NOW()
)
ON CONFLICT (username) DO UPDATE
    SET password_hash = EXCLUDED.password_hash,
        updated_at    = NOW();


-- ── Verify ────────────────────────────────────────────────────────────────────
SELECT id, username, display_name, role, online, created_at
FROM users
ORDER BY created_at;
